name: Build and Deploy
env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USE_GITHUB_DATA: "true"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Update npm 🚀
        run: npm install -g npm@latest

      - name: Install Dependencies 🔧
        run: npm install

      - name: Fix Format 🪄
        # This fixes the formatting issues in fetch.js and portfolio.js automatically
        run: npx prettier --write "./**/*.{js,css,json,scss}" || true

      - name: Build 🔧
        run: npm run build
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main 
          FOLDER: build
          CLEAN: true
